package medicamentosbd.Paneles;

import BD.ConexionBD;
import Controlador.Modelo_Administracion;
import Controlador.Modelo_Composicion;
import Controlador.Modelo_Ingreso;
import Controlador.Modelo_Lista;
import Controlador.Modelo_Medicamento;
import Controlador.Modelo_Paciente;
import Controlador.Modelo_Personal;
import Controlador.Modelo_Prescripcion;
import Controlador.Modelo_PrincipioActivo;
import Vistas.Inserts.Formulario_Insert_Activos;
import Vistas.Inserts.Formulario_Insert_Administracion;
import Vistas.Inserts.Formulario_Insert_Composicion;
import Vistas.Inserts.Formulario_Insert_Lista;
import Vistas.Inserts.Formulario_Insert_Medicamento;
import Vistas.Inserts.JFIngreso;
import Vistas.Inserts.JFPaciente;
import Vistas.Inserts.JFPersonal;
import Vistas.Inserts.JFPrescripcion;

public class Insertar extends javax.swing.JPanel {

    ConexionBD Conexion_Actual=new ConexionBD(); 
    Modelo_Administracion M_Adm; 
    Modelo_Composicion M_Comp; 
    Modelo_Ingreso M_Ing; 
    Modelo_Lista M_Lis; 
    Modelo_Medicamento M_Medicamento; 
    Modelo_Paciente M_Pac;
    Modelo_Personal M_Per;
    Modelo_Prescripcion M_Pres;
    Modelo_PrincipioActivo M_Pri; 
    public Insertar(Modelo_Administracion M_Adm, Modelo_Composicion M_Comp, Modelo_Ingreso M_Ing, 
            Modelo_Lista M_Lis,Modelo_Medicamento M_Medicamento,Modelo_Paciente M_Pac,Modelo_Personal M_Per,
            Modelo_Prescripcion M_Pres,Modelo_PrincipioActivo M_Pri) {
        initComponents();
        this.M_Adm=M_Adm; 
        this.M_Comp=M_Comp;
        this.M_Ing=M_Ing; 
        this.M_Lis=M_Lis;
        this.M_Medicamento=M_Medicamento;
        this.M_Pac=M_Pac; 
        this.M_Per=M_Per;
        this.M_Pres=M_Pres;
        this.M_Pri=M_Pri;
        this.setVisible(true);
        String[] Tablas={
            "Administracion", "Composicion", "Ingreso", "Lista", "Medicamento",
            "Paciente", "Personal", "Prescripcion", "PrincipioActivo"
        };
        this.Cb_Tablas.removeAllItems();
        for(String tabla : Tablas){
            Cb_Tablas.addItem(tabla);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_Insertar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Cb_Tablas = new javax.swing.JComboBox<>();
        B_Formulario = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Selecciona una Tabla:");

        Cb_Tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        B_Formulario.setText("Ver Formulario");
        B_Formulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FormularioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_InsertarLayout = new javax.swing.GroupLayout(P_Insertar);
        P_Insertar.setLayout(P_InsertarLayout);
        P_InsertarLayout.setHorizontalGroup(
            P_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_InsertarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cb_Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(B_Formulario)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        P_InsertarLayout.setVerticalGroup(
            P_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_InsertarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(P_InsertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Cb_Tablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Formulario))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void B_FormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FormularioActionPerformed
        String Tabla_Seleccionada=this.Cb_Tablas.getSelectedItem().toString();
        switch (Tabla_Seleccionada){
            case "Administracion":
            Formulario_Insert_Administracion Administracion=new Formulario_Insert_Administracion(M_Adm,M_Per,M_Lis);
            Administracion.setVisible(true);
            break;
            case "Composicion":
            Formulario_Insert_Composicion Composicion=new Formulario_Insert_Composicion(M_Comp,M_Medicamento,M_Pri);
            Composicion.setVisible(true);
            break;
            case "Ingreso":
            JFIngreso Ingreso=new JFIngreso();
            Ingreso.setVisible(true);
            break;
            case "Lista":
            Formulario_Insert_Lista Lista=new Formulario_Insert_Lista(M_Lis, M_Medicamento,M_Pres,M_Adm);
            Lista.setVisible(true);
            break;
            case "Medicamento":
            Formulario_Insert_Medicamento Medicamento=new Formulario_Insert_Medicamento(M_Medicamento,M_Comp);
            Medicamento.setVisible(true);
            break;
            case "Paciente":
            JFPaciente Paciente=new JFPaciente();
            Paciente.setVisible(true);
            break;
            case "Personal":
            JFPersonal Personal=new JFPersonal();
            Personal.setVisible(true);
            break;
            case "Prescripcion":
            JFPrescripcion Prescripcion=new JFPrescripcion();
            Prescripcion.setVisible(true);
            break;
            case "PrincipioActivo":
            Formulario_Insert_Activos Activos=new Formulario_Insert_Activos(M_Pri,M_Comp);
            Activos.setVisible(true);
            break;

        }
    }//GEN-LAST:event_B_FormularioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Formulario;
    private javax.swing.JComboBox<String> Cb_Tablas;
    private javax.swing.JPanel P_Insertar;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
